### ISSUE TITLE
build31: no menu

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-plugin#12]
EDIT: with build 31 no menu is showing for me, builds up to 26 are working OK. 
I have not setup any script-opts/menu.conf. 
There are no errors in the log-file: 
[   0.010][d][menu] Loading cplugin script c:/mpc/mpv/portable_config/scripts/menu.dll...
I've tried --input-conf with a minimal input.conf and --no-config --scripts=portable_config/scripts/menu.dll with no success.

**Comment by tsl0922** [comment]
a keybinding is required now:
```
MBTN_RIGHT script-message-to menu show
```

**Comment by butterw** [comment]
As explained in the readme, to display the menu the input.conf file needs to be edited (or created).
It is preferable to add keybinding(s) to display the menu at the end of input.conf to ensure they are always active. 
To bind the menu key:
MENU script-message-to menu show
