### ISSUE TITLE
gray out empty track list (audio, video, subtitles) like chapters  

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-plugin#14]
Is it possible to gray out the track list for audio, video, subtitles when no tracks are loaded like for chapters ?

Currently for audio and video, the entry is not grayed even if empty.
For subtitles the option for switching off subtitles is provided even if there are no subtitles loaded.

**Comment by tsl0922** [comment]
It's already disabled, do you mean change the disabled color to gray?

**Comment by butterw** [comment]
yes. this is useful to know if a file has audio or subs available. 
Ex: no point in clicking on chapters, if chapters is grayed out then this means the file doesn't have chapters.

**Comment by tsl0922** [comment]
It's changed in a37d6b37aa1f75ae022439334be4e1c51f70e828

**Comment by butterw** [comment]
I'm not seeing any change with the latest build. 
Chapter times are now displayed. But with a video file without audio or subtitles, I still get: 
- Audio (disabled but not grayed) >
- Subtitle > Off.

**Comment by tsl0922** [comment]
Fixed the empty menu may not disabled issue.

The "gray" set here is a menu flag from system api, since we are not drawing the text ourself.
