### ISSUE TITLE
Bug: the latest commit broke compatibility with other scripts and caused a crash

### ISSUE THREAD

**Issue by dyphire** [tsl0922/mpv-plugin#2]
Opening mpv pops up the following window, which also causes the application to fail to close properly
![image](https://github.com/tsl0922/mpv-plugin/assets/61936050/a05578ad-acd8-4255-bd4c-c8a5c3249ede)  ![image](https://github.com/tsl0922/mpv-plugin/assets/61936050/1fc14b51-47b7-4967-b412-e48695b79f04)

**Comment by tsl0922** [comment]
This a debug message (plugin receives `script-message` from some script), I've removed it from the latest code.
