### ISSUE TITLE
Text size adjustment (fullscreen startup)

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-plugin#5]
> Some text size customization options would be nice to have.
> Different settings could be used for fullscreen (plenty of room to display a contextual menu) and in windowed mode (ex: on a 360p video).

The menu should not have any custom options other than custom menu items, it is not a UI.
_Originally posted by @dyphire in https://github.com/tsl0922/mpv-plugin/issues/1#issuecomment-1854982332_

I'm using a monitor and I've set up my windows hidpi setting (a bit small) for productivity apps. But the requirements are different if I'm wiewing a movie 2m away from the screen (I need bigger text) and I don't want to have to adjust my hidpi settings just for one app.

This feature request (if feasible) is for a text-size increase parameter applied at startup if mpv is started fullscreen.

**Comment by tsl0922** [comment]
I think this issue can be merged to #1 now.
