### ISSUE TITLE
show &

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-plugin#6]
& is not shown in menu (shortcut or entry)   

Alt+& 	show-text hello  		#menu: mpv-plugin
Ctrl+a	show-text hello  		#menu: P&S > bar

EDIT: for the second case it's possible to escape & 
Ctrl+a	show-text hello  		#menu: P&&S > bar

but this approach doesn't work in the first case with the mpv shortcut, because mpv doesn't recognise Alt+&&.

**Comment by butterw** [comment]
& is part of the default mpv.net input.conf, so it should be up to the parser to the required escaping of input.conf:  
Ctrl++      add video-zoom  0.1    #menu: Pan & Scan > Increase Size

**Comment by tsl0922** [comment]
fixed on latest main branch.
