### ISSUE TITLE
Features: Add keybind when menu open

### ISSUE THREAD

**Issue by Youxikong** [tsl0922/mpv-plugin#7]
In previous verion, like case 2 of #6 , if I add this line to input.conf:
```
_                  script-binding uosc/open-file                         #! 加载 (&F) > 文件浏览器
_                  script-binding uosc/load-subtitles                    #! 字幕轨 (&S)
```
When menu open, I can trigger command or expand submenu by pressing the key "F" or "S".
This feature (or bug) has been removed in the latest version, could you readd it?

**Comment by tsl0922** [comment]
I don't think this feature is useful.

**Comment by dyphire** [comment]
I also feel that this feature is not useful. 
The menu is used to open and click on operations. The behavior of specifying additional dynamic key bindings for custom operations when the menu is open is somewhat strange. If this is a playlist or chapter menu, then dynamic key binding is more meaningful.

**Comment by Youxikong** [comment]
You're right, mpv's key bindings configuration is powerful enough. Dynamic key bindings when menu open is unnecessary and confusing.

**Comment by butterw** [comment]
This is a standard windows menu: when a menu is open, the first letter of menu items acts as a keyboard accelerator.
