### ISSUE TITLE
issues with Comments

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-plugin#8]
In the latest builds, the following commented out command is now shown in menu. The command will not be executed because it's a comment for mpv:
` # Shift+a	show-text hello  	#menu: ..helloA`

[input] Command 'Shift+a' not found.
[input] Command was defined at menu.

Menu should ignore lines that are commented out for mpv.  Users need to be able to comment out lines in input.conf to adjust their config, menu should not interfere.

A second request would be to support a syntax (maybe ## ?) for same line comments not to be displayed in the menu: 
` Shift+b	show-text hello  	#menu: ..helloB ## this is a user comment that should not be printed to menu.`
the command ..hello should be printed out in the menu but not the comment.
Same line comment are useful because it is immediately clear what line they apply to and they allow for a more compact input.conf file.

**Comment by dyphire** [comment]
The cplugin menu now supports using the `#` character tospecify menu content without key binding. This is the menu syntax in UOSC, which is better than using the `_` character to specify menu syntax without key binding in mpvv.net. The special syntax in mpv.net is not supported by mpv and occupies the key binding of `_`.

The cplugin menu still supports comments, but comments should not include the menu syntax of `#!` or `#menu:`. Just adjust your annotation habits instead of asking the script to abandon new features.

> Menu should ignore lines that are commented out for mpv. Users need to be able to comment out lines in input.conf to adjust their config, menu should not interfere.
> 
> A second request would be to support a syntax (maybe ## ?) for same line comments not to be displayed in the menu: ` Shift+b show-text hello #menu: ..helloB ## this is a user comment that should not be printed to menu.` the command ..hello should be printed out in the menu but not the comment. Same line comment are useful because it is immediately clear what line they apply to and they allow for a more compact input.conf file.

Supporting same line comments makes sense and is also supported in uosc's menu syntax.

**Comment by butterw** [comment]
This issue is about 2 things:
1) commenting out a line in input.conf to disable it. 
2) a request (if feasible) for a menu + user comment syntax. 
Provide an example of solutions.

With regards to 1) I wouldn't expect mpv users to adjust their habits to conform to a specific (seemingly bad) uosc syntax. Rather I would expect uosc to improve its syntax as needed. The mpv.net syntax may not be perfect, but it's simple and does work.

Right now the situation with mpv-plugin is that if a mpv command with a menu entry is commented out with # (to disable it), it will appear in the menu. And using it then generates an error. This is broken for me.

**Comment by hooke007** [comment]
The mpv.net syntax is obviously worse than uosc's. It's unacceptable for those who use the key of `_`

**Comment by tsl0922** [comment]
I agree uosc syntax mess it, it's hard to detect where it is a keybind + cmd or cmd in this situation.

I'm going to add some option to toggle uosc mode.

**Comment by tsl0922** [comment]
inline comments in menu syntax in supported now.

**Comment by tsl0922** [comment]
> I'm going to add some option to toggle uosc mode.

It is supported via `uosc=yes` in `~~/script-opts/menu.conf` now, disabled by default.

**Comment by butterw** [comment]
> The mpv.net syntax is obviously worse than uosc's. It's unacceptable for those who use the key of `_`
Neither mpv.net nor uosc are primarily projects about the context menu, and it's obvious the mpv.net syntax is a hack. 
The #menu: syntax is very readable and searchable when editing input.conf. _ ignore is at least searchable and doesn't cause the issue 

I'm not really familiar with uosc, but is there a valid reason why the supported syntax couldn't be tweaked to avoid the issue with with commented out lines. 
" uosc, Adding items to menu: 
Use # instead of a key if you don't necessarily want to bind a key to a command, but still want it in the menu."
Couldn't something like #!! be used instead of just # ?

**Comment by hooke007** [comment]
> I'm not really familiar with uosc

True. uosc also uses `#menu:`

>  _ ignore is at least searchable and doesn't cause the issue

>>The special syntax in mpv.net is not supported by mpv and occupies the key binding of _.
>> It's unacceptable for those who use the key of _

That's the big problem for me and why I don't recognise.

**Comment by Mark-Joy** [comment]
Hello, I am probably late to the party, but there's an easy solution to this issue.
We can have a rule to recognize a user comment instead of an uosc's menu syntax:
- `#` followed by a `whitespace` (space, tab) is an uosc's menu syntax.
- `#` followed by any other character except `whitespace` is an user comment.

Example:
- uosc's menu syntax
```
#    #! Title
#    #! Section > Title
```
- user comments:
```
#Shift+a	show-text hello  	#menu: ..hello
#Shift+b	show-text world  	#menu: ..world
```

**Comment by hooke007** [comment]
uosc's menu syntax is designed for compatibility with UOSC firstly.
Why do you want to remove it?

**Comment by Mark-Joy** [comment]
> Why do you want to remove it?

I don't want to remove it. Why would I?
What I suggested was a way to determine an `#` user comment and an `#` uosc's menu syntax.
It's actually in the current code of uosc. It's how `uosc` use to differentiate between user comments and it's syntax for keyless menu-item:
> Use # instead of a key if you don't necessarily want to bind a key to a command

https://github.com/tomasklaen/uosc/blob/b01c6df787c4ac0f3e5603286c30741cf39467e9/src/uosc/lib/menus.lua#L392-L395

**Comment by dyphire** [comment]
In fact uosc has added support for the comment menu syntax: https://github.com/tomasklaen/uosc/commit/d4b1343609434a61e45da7d654f69eea6a0dc17c
It is indeed necessary to update the relevant uosc menu syntax in the mpv-menu-plugin scripts.
